"""Export the local scripture data for the app (per-book JSON + a require map).

Usage:  python scripts/export_scripture.py

Reads  data/scripture.en.json, data/scripture.am.json (gitignored)
       src/data/canon.json
Writes assets/scripture/<book-id>.json   (gitignored)
       src/scripture/generated.ts        (gitignored; the app tolerates its absence)

Each book file: {"id", "en": {chapter: {verse: text}} | null, "am": ... | null}.
A verse key may be a range like "3-4" (Amharic prints some verses together);
key "0" is a psalm title.
"""
import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load(path):
    p = os.path.join(ROOT, path)
    if not os.path.exists(p):
        return {}
    with io.open(p, encoding="utf-8") as f:
        return {b["id"]: b["chapters"] for b in json.load(f)}


def main():
    en = load("data/scripture.en.json")
    am = load("data/scripture.am.json")
    with io.open(os.path.join(ROOT, "src", "data", "canon.json"), encoding="utf-8") as f:
        canon = json.load(f)

    out_dir = os.path.join(ROOT, "assets", "scripture")
    os.makedirs(out_dir, exist_ok=True)
    gen_dir = os.path.join(ROOT, "src", "scripture")
    os.makedirs(gen_dir, exist_ok=True)

    lines = [
        "// GENERATED by scripts/export_scripture.py. Do not edit or commit.",
        "type Loader = () => unknown;",
        "export const loaders: Record<string, Loader> = {",
    ]
    total = 0
    for b in canon:
        bid = b["id"]
        e = en.get(bid) or None
        a = am.get(bid) or None
        if not e and not a:
            continue
        path = os.path.join(out_dir, f"{bid}.json")
        with io.open(path, "w", encoding="utf-8", newline="\n") as f:
            json.dump({"id": bid, "en": e, "am": a}, f, ensure_ascii=False, separators=(",", ":"))
        total += os.path.getsize(path)
        lines.append(f"  '{bid}': () => require('../../assets/scripture/{bid}.json'),")
    lines.append("};")
    lines.append("export const availability: Record<string, { en: boolean; am: boolean }> = {")
    for b in canon:
        lines.append(f"  '{b['id']}': {{ en: {str(bool(en.get(b['id']))).lower()}, am: {str(bool(am.get(b['id']))).lower()} }},")
    lines.append("};")
    with io.open(os.path.join(gen_dir, "generated.ts"), "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    have = sum(1 for b in canon if en.get(b["id"]) or am.get(b["id"]))
    print(f"{have}/81 books exported, {total / 1e6:.1f} MB")
    print(f"English: {sum(1 for b in canon if en.get(b['id']))}  Amharic: {sum(1 for b in canon if am.get(b['id']))}")


if __name__ == "__main__":
    main()
